name: Deploy to Hostinger

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          cd frontend
          npm install

      - name: Build project
        run: |
          cd frontend
          npm run build

      - name: Deploy to Hostinger
        uses: SamKirkland/web-deploy@v1
        with:
          server: ftp.openmeme.in
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          remote-path: public_html
          local-path: frontend/dist